# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    node: circleci/node@5.0.0
    cypress: cypress-io/cypress@1.29.0
    codecov: codecov/codecov@3.2.2

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

workflows:
    example-workflow:
        jobs: 
            - node/test:
                    pkg-manager: npm
                    test-results-for: other
                    run-command: test:ci
            - cypress/run:
                start: npm start
            