# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
    node: circleci/node@5.0.0
    codecov: codecov/codecov@3.2.2
    cypress: samuelboland/cypress@0.0.12


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Jobs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

jobs:
    Build_and_run_cypress:
        environment:
            CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

        executor: with-chrome
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - cache-v1-{{ checksum "package.json"}}
            - run:
                  name: 'Install'
                  command: npm install
                  working_directory: ''
            - run:
                  name: 'Verify Cypress'
                  command: npx cypress verify
                  working_directory: ''
            - run:
                  name: 'Build'
                  command: 'npm run build'
                  working_directory: ''
            - save_cache:
                  key: cache-v1-{{ checksum "package.json"}}
                  paths:
                      - ~/.npm
                      - ~/.cache
                      - .next/cache
            - run:
                  name: 'Start'
                  command: 'npm run start'
                  background: true
                  working_directory: ''
            - run:
                  name: Wait-on 'http-get://localhost:3000'
                  command: npx wait-on 'http-get://localhost:3000'
            - run: 
                  name: Run cypress tests
                  no_output_timeout: 10m
                  command: npx cypress run --browser chrome
                  working_directory: ''
            - store_artifacts: 
                  path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
            - store_artifacts:
                path: coverage

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Executors for Cypress ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# List of executors can be found here: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
executors:
    with-chrome:
        docker:
            - image: 'cypress/browsers:node16.5.0-chrome97-ff96'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
    Application Test:
        jobs:
            - node/test:
                  pkg-manager: npm
                  test-results-for: other
                  run-command: test:ci
                  post-steps:
                      - store_artifacts:
                            path: coverage
                      - codecov/upload
            - Build_and_run_cypress:
                  post-steps: 
                      - codecov/upload
