# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    node: circleci/node@5.0.0
    codecov: codecov/codecov@3.2.2
    cypress: samuelboland/cypress@0.0.12

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Jobs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Executors for Cypress ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# List of executors can be found here: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
executors:
    with-chrome:
        docker:
            - image: 'cypress/browsers:node16.5.0-chrome97-ff96'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
    Application Test:
        jobs:
            - node/test:
                  pkg-manager: npm
                  test-results-for: other
                  run-command: test:ci
                  post-steps:
                      - store_artifacts:
                            path: coverage
                      - codecov/upload
            - cypress/install:
                  build: npm run build
                  cache-key: cache-{{ checksum "package.json"}}
            - cypress/run:
                  cache-key: cache-{{ checksum "package.json"}}
                  store_artifacts: true
                  executor: with-chrome
                  browser: chrome
                  requires:
                      - cypress/install
                  attach-workspace: true
                  start: npm run start
                  wait-on: 'http-get://localhost:3000'
                  post-steps:
                      - store_artifacts:
                            path: coverage
                      - codecov/upload
